/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IG;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author perla
 */
public class Devoluciones extends javax.swing.JPanel {

    /**
     * Creates new form Devoluciones
     */
    public Devoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        lbl_bus2 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txt_isbn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_usuario = new javax.swing.JLabel();
        cmd_entrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 300, 10));

        lbl_bus2.setFont(new java.awt.Font("STIXIntegralsUp", 1, 36)); // NOI18N
        lbl_bus2.setText("Devolucion de Libro");
        add(lbl_bus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 370, 50));

        lbl_name.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_name.setText("Folio de Usuario");
        add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txt_name.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_name.setForeground(new java.awt.Color(102, 102, 102));
        txt_name.setText("Ingrese el folio de usuario");
        txt_name.setBorder(null);
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });
        txt_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nameMousePressed(evt);
            }
        });
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, 30));

        jSeparator4.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 10));

        txt_isbn.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_isbn.setForeground(new java.awt.Color(102, 102, 102));
        txt_isbn.setText("Ingrese el ISBN del libro");
        txt_isbn.setToolTipText("Ingrese el ISBN");
        txt_isbn.setBorder(null);
        txt_isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_isbnFocusLost(evt);
            }
        });
        txt_isbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_isbnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_isbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_isbnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_isbnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_isbnMouseReleased(evt);
            }
        });
        txt_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbnActionPerformed(evt);
            }
        });
        add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 30));

        jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, -1));

        lbl_usuario.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_usuario.setText("ISBN");
        add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        cmd_entrar.setBackground(new java.awt.Color(153, 102, 0));
        cmd_entrar.setForeground(new java.awt.Color(166, 110, 0));
        cmd_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmd_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmd_entrarMousePressed(evt);
            }
        });
        cmd_entrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("STIXIntegralsUp", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Devolver");
        cmd_entrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(cmd_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/giphy.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 420, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusLost
        if(txt_name.getText().equals("")){
            txt_name.setText("Ingrese el folio de usuario");
            txt_name.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_nameFocusLost

    private void txt_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nameMousePressed
        if(txt_name.getText().equals("Ingrese el folio de usuario")){
            txt_name.setText("");
            txt_name.setForeground(Color.black);}
    }//GEN-LAST:event_txt_nameMousePressed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_isbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_isbnFocusLost
        if(txt_isbn.getText().equals("")){
            txt_isbn.setText("Ingrese el ISBN del libro");
            txt_isbn.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_isbnFocusLost

    private void txt_isbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseClicked

    private void txt_isbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseEntered

    }//GEN-LAST:event_txt_isbnMouseEntered

    private void txt_isbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseExited

    }//GEN-LAST:event_txt_isbnMouseExited

    private void txt_isbnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMousePressed
        if(txt_isbn.getText().equals("Ingrese el ISBN del libro")){
            txt_isbn.setText("");
            txt_isbn.setForeground(Color.black);}
    }//GEN-LAST:event_txt_isbnMousePressed

    private void txt_isbnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseReleased

    private void txt_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnActionPerformed

    private void cmd_entrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_entrarMousePressed
    int isbn = Integer.parseInt(txt_isbn.getText());
    //int id_us = Integer.parseInt(txt_name.getText());
        int cantidad_actual = 0;
        try {
            Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
            String insertarsql2 = "SELECT Cant FROM dbo.Libros WHERE ISBN=" + isbn + ";";
            ResultSet rs = sql.executeQuery(insertarsql2);
            rs.next();
            cantidad_actual = rs.getInt("Cant");
            cantidad_actual = cantidad_actual + 1;
               System.out.println(cantidad_actual);
            String insertarsql = "UPDATE dbo.Libros SET Cant=" + cantidad_actual + " WHERE ISBN='" + isbn + "';";
            sql.executeQuery(insertarsql);
        } catch (SQLException | NumberFormatException e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_cmd_entrarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cmd_entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_bus2;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
