/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IG;

import java.awt.BorderLayout;

/*
 * @author aylin
 */
public class Inicio extends javax.swing.JFrame {
    int flag = 0;
            int xMouse, yMouse;

    public void setFlag(int flag) {
        this.flag = flag;
    }

    public int getFlag() {
        return flag;
    }
            
           
   
    public Inicio() {
        initComponents();
        Principal p = new Principal(); //Principal = nombre del panel 
        p.setSize(669,503);
        p.setLocation(0,0); 
        
      
        contenido.removeAll(); //contenido = panel donde se importara el panel ya de
        contenido.add(p,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_libros2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_salir = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        lbl_cuenta = new javax.swing.JLabel();
        lbl_inicio = new javax.swing.JLabel();
        lbl_prestamo = new javax.swing.JLabel();
        lbl_libros = new javax.swing.JLabel();
        lbl_cuenta1 = new javax.swing.JLabel();
        lbl_libros3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_inicio1 = new javax.swing.JLabel();
        lbl_prove = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Mover = new javax.swing.JPanel();

        lbl_libros2.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl_libros2.setForeground(new java.awt.Color(204, 102, 0));
        lbl_libros2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_libros2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/file-chart.png"))); // NOI18N
        lbl_libros2.setText("Reportes");
        lbl_libros2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lbl_libros2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_libros2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_libros2.setIconTextGap(15);
        lbl_libros2.setName("lbl_consultas"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 225, 198));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        lbl_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir2.png"))); // NOI18N
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_salirMousePressed(evt);
            }
        });
        getContentPane().add(lbl_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        Menu.setBackground(new java.awt.Color(234, 225, 198));
        Menu.setName(""); // NOI18N
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cuenta.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl_cuenta.setForeground(new java.awt.Color(204, 102, 0));
        lbl_cuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_cuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/account-multiple.png"))); // NOI18N
        lbl_cuenta.setText("Cliente");
        lbl_cuenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lbl_cuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cuenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_cuenta.setIconTextGap(15);
        lbl_cuenta.setName("lbl_cuenta"); // NOI18N
        lbl_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_cuentaMousePressed(evt);
            }
        });
        Menu.add(lbl_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 217, 50));

        lbl_inicio.setFont(new java.awt.Font("STIXIntegralsUp", 0, 24)); // NOI18N
        lbl_inicio.setForeground(new java.awt.Color(204, 102, 0));
        lbl_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/barco.png"))); // NOI18N
        lbl_inicio.setText("Inicio");
        lbl_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_inicio.setIconTextGap(15);
        lbl_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_inicioMouseClicked(evt);
            }
        });
        Menu.add(lbl_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 60, 58));

        lbl_prestamo.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl_prestamo.setForeground(new java.awt.Color(204, 102, 0));
        lbl_prestamo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_prestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calendar-plus.png"))); // NOI18N
        lbl_prestamo.setText("Prestamo");
        lbl_prestamo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lbl_prestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_prestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_prestamo.setIconTextGap(15);
        lbl_prestamo.setName("lbl_consultas"); // NOI18N
        lbl_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_prestamoMouseClicked(evt);
            }
        });
        Menu.add(lbl_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 204, 50));

        lbl_libros.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl_libros.setForeground(new java.awt.Color(204, 102, 0));
        lbl_libros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/book-open-page-variant.png"))); // NOI18N
        lbl_libros.setText("Libros");
        lbl_libros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lbl_libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_libros.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_libros.setIconTextGap(15);
        lbl_libros.setName("lbl_consultas"); // NOI18N
        lbl_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_librosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_librosMousePressed(evt);
            }
        });
        Menu.add(lbl_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 216, 50));

        lbl_cuenta1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl_cuenta1.setForeground(new java.awt.Color(204, 102, 0));
        lbl_cuenta1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_cuenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrarSesion.png"))); // NOI18N
        lbl_cuenta1.setText("Cerrar Sesion");
        lbl_cuenta1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lbl_cuenta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cuenta1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_cuenta1.setIconTextGap(10);
        lbl_cuenta1.setName("lbl_cuenta"); // NOI18N
        lbl_cuenta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cuenta1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_cuenta1MousePressed(evt);
            }
        });
        Menu.add(lbl_cuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 217, 50));

        lbl_libros3.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl_libros3.setForeground(new java.awt.Color(204, 102, 0));
        lbl_libros3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_libros3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calendar-multiple-check.png"))); // NOI18N
        lbl_libros3.setText("Devoluciones");
        lbl_libros3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lbl_libros3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_libros3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_libros3.setIconTextGap(15);
        lbl_libros3.setName("lbl_consultas"); // NOI18N
        lbl_libros3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_libros3MousePressed(evt);
            }
        });
        Menu.add(lbl_libros3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 216, 50));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, 217, 10));
        Menu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 206, 10));

        lbl_inicio1.setFont(new java.awt.Font("STIXIntegralsUp", 0, 24)); // NOI18N
        lbl_inicio1.setForeground(new java.awt.Color(204, 102, 0));
        lbl_inicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/home-outline.png"))); // NOI18N
        lbl_inicio1.setText("Inicio");
        lbl_inicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_inicio1.setIconTextGap(15);
        lbl_inicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_inicio1MouseClicked(evt);
            }
        });
        Menu.add(lbl_inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 207, 58));

        lbl_prove.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl_prove.setForeground(new java.awt.Color(204, 102, 0));
        lbl_prove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prove.png"))); // NOI18N
        lbl_prove.setText("Proveedores");
        lbl_prove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_prove.setIconTextGap(15);
        lbl_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_proveMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_proveMousePressed(evt);
            }
        });
        Menu.add(lbl_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 170, 40));

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 640));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(669, 503));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        getContentPane().add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 680, 503));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/libros3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 680, 620));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        Mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverMouseDragged(evt);
            }
        });
        Mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MoverLayout = new javax.swing.GroupLayout(Mover);
        Mover.setLayout(MoverLayout);
        MoverLayout.setHorizontalGroup(
            MoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        MoverLayout.setVerticalGroup(
            MoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(Mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverMousePressed
      xMouse = evt.getX();
      yMouse = evt.getY();
    }//GEN-LAST:event_MoverMousePressed

    private void MoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverMouseDragged
       int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_MoverMouseDragged

    private void lbl_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMousePressed
        System.exit(0);
    }//GEN-LAST:event_lbl_salirMousePressed

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void lbl_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_prestamoMouseClicked
      Prestamo pre = new Prestamo(); //Principal = nombre del panel 
        pre.setSize(669,503);
        pre.setLocation(0,0); 
        
      
        contenido.removeAll(); //contenido = panel donde se importara el panel ya de
        contenido.add(pre,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint(); 
    }//GEN-LAST:event_lbl_prestamoMouseClicked

    private void lbl_inicioMouseClicked(java.awt.event.MouseEvent evt) {                                        
        
                                                

    }                                       

    private void lbl_librosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_librosMouseClicked
        
    }//GEN-LAST:event_lbl_librosMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void lbl_cuenta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cuenta1MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_lbl_cuenta1MouseClicked

    private void lbl_cuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cuentaMousePressed
        Usuario us = new Usuario(); //Principal = nombre del panel 
        us.setSize(669,503);
        us.setLocation(0,0); 
        
        contenido.removeAll(); //contenido = panel donde se importara el panel ya de
        contenido.add(us,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_lbl_cuentaMousePressed

    private void lbl_inicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_inicio1MouseClicked
Principal p = new Principal(); //Principal = nombre del panel 
        p.setSize(669,503);
        p.setLocation(0,0); 
        
      
        contenido.removeAll(); //contenido = panel donde se importara el panel ya de
        contenido.add(p,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();            // TODO add your handling code here:
    }//GEN-LAST:event_lbl_inicio1MouseClicked

    private void lbl_libros3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_libros3MousePressed
        Devoluciones dev = new Devoluciones(); //Principal = nombre del panel 
        dev.setSize(669,503);
        dev.setLocation(0,0); 
        
        contenido.removeAll(); //contenido = panel donde se importara el panel ya de
        contenido.add(dev,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_lbl_libros3MousePressed

    private void lbl_proveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_proveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_proveMouseClicked

    private void lbl_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_proveMousePressed
          Proveedor prov = new Proveedor(); //Principal = nombre del panel 
        prov.setSize(669,503);
        prov.setLocation(0,0); 
        
        contenido.removeAll(); //contenido = panel donde se importara el panel ya de
        contenido.add(prov,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_lbl_proveMousePressed

    private void lbl_librosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_librosMousePressed
        Insertar i = new Insertar(); //Principal = nombre del panel 
        i.jPanel1.setSize(669,503);
        i.jPanel1.setLocation(0,0); 
        
        contenido.removeAll(); //contenido = panel donde se importara el panel ya de
        contenido.add(i.jPanel1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_lbl_librosMousePressed

    private void lbl_cuenta1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cuenta1MousePressed
        Sesion ini = new Sesion();
        ini.setVisible(true);
        this.setVisible(false);          
    }//GEN-LAST:event_lbl_cuenta1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Mover;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_cuenta;
    private javax.swing.JLabel lbl_cuenta1;
    private javax.swing.JLabel lbl_inicio;
    private javax.swing.JLabel lbl_inicio1;
    private javax.swing.JLabel lbl_libros;
    private javax.swing.JLabel lbl_libros2;
    private javax.swing.JLabel lbl_libros3;
    private javax.swing.JLabel lbl_prestamo;
    private javax.swing.JLabel lbl_prove;
    private javax.swing.JLabel lbl_salir;
    // End of variables declaration//GEN-END:variables
}
