/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IG;

import IG.ConnectionSQL;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author aylin
 */
public class Insertar extends javax.swing.JFrame {
    
    /**
     * Creates new form Insertar
     */
    public Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_isbn = new javax.swing.JTextField();
        lbl_usuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_titulo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_autor = new javax.swing.JTextField();
        lbl_autor = new javax.swing.JLabel();
        lbl_editorial = new javax.swing.JLabel();
        txt_editorial = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_genero = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_descripcion = new javax.swing.JTextField();
        lbl_descripcion = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lbl_pagina = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_pagina = new javax.swing.JTextField();
        lbl_cantidad = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txt_cantidad = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_edicion = new javax.swing.JTextField();
        lbl_sesion1 = new javax.swing.JLabel();
        lbl_sesion2 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        lbl_sesion3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("Ingrese el ISBN");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, -1));

        txt_isbn.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_isbn.setForeground(new java.awt.Color(102, 102, 102));
        txt_isbn.setText("Ingrese el ISBN");
        txt_isbn.setToolTipText("Ingrese el ISBN");
        txt_isbn.setBorder(null);
        txt_isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_isbnFocusLost(evt);
            }
        });
        txt_isbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_isbnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_isbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_isbnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_isbnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_isbnMouseReleased(evt);
            }
        });
        txt_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbnActionPerformed(evt);
            }
        });
        jPanel1.add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 210, 30));

        lbl_usuario.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_usuario.setText("ISBN");
        jPanel1.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, -1));

        txt_titulo.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(102, 102, 102));
        txt_titulo.setText("Ingrese el Titulo");
        txt_titulo.setBorder(null);
        txt_titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tituloFocusLost(evt);
            }
        });
        txt_titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tituloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_tituloMousePressed(evt);
            }
        });
        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });
        jPanel1.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 210, 30));

        lbl_titulo.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_titulo.setText("Titulo");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, -1));

        txt_autor.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_autor.setForeground(new java.awt.Color(102, 102, 102));
        txt_autor.setText("Ingrese el autor");
        txt_autor.setBorder(null);
        txt_autor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_autorFocusLost(evt);
            }
        });
        txt_autor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_autorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_autorMousePressed(evt);
            }
        });
        txt_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 30));

        lbl_autor.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_autor.setText("Autor");
        jPanel1.add(lbl_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lbl_editorial.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_editorial.setText("Editorial");
        jPanel1.add(lbl_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txt_editorial.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_editorial.setForeground(new java.awt.Color(102, 102, 102));
        txt_editorial.setText("Ingrese la editorial");
        txt_editorial.setBorder(null);
        txt_editorial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_editorialFocusLost(evt);
            }
        });
        txt_editorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_editorialMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_editorialMousePressed(evt);
            }
        });
        txt_editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_editorialActionPerformed(evt);
            }
        });
        jPanel1.add(txt_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 210, 30));

        jSeparator4.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, -1));

        lbl_genero.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_genero.setText("Genero");
        jPanel1.add(lbl_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        txt_genero.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_genero.setForeground(new java.awt.Color(102, 102, 102));
        txt_genero.setText("Ingrese el genero");
        txt_genero.setBorder(null);
        txt_genero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_generoFocusLost(evt);
            }
        });
        txt_genero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_generoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_generoMousePressed(evt);
            }
        });
        txt_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_generoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 210, 30));

        jSeparator5.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator5.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 210, -1));

        txt_descripcion.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_descripcion.setForeground(new java.awt.Color(102, 102, 102));
        txt_descripcion.setText("Ingrese alguna descripcion");
        txt_descripcion.setBorder(null);
        txt_descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_descripcionFocusLost(evt);
            }
        });
        txt_descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_descripcionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_descripcionMousePressed(evt);
            }
        });
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 210, 30));

        lbl_descripcion.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_descripcion.setText("Descripcion");
        jPanel1.add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator6.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 210, -1));

        lbl_pagina.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_pagina.setText("Paginas");
        jPanel1.add(lbl_pagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 70, 10));

        txt_pagina.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_pagina.setForeground(new java.awt.Color(102, 102, 102));
        txt_pagina.setText("No. paginas");
        txt_pagina.setBorder(null);
        txt_pagina.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_paginaFocusLost(evt);
            }
        });
        txt_pagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_paginaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_paginaMousePressed(evt);
            }
        });
        txt_pagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paginaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, 30));

        lbl_cantidad.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_cantidad.setText("Cantidad");
        jPanel1.add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 100, 10));

        txt_cantidad.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_cantidad.setForeground(new java.awt.Color(102, 102, 102));
        txt_cantidad.setText("No. libros");
        txt_cantidad.setBorder(null);
        txt_cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cantidadFocusLost(evt);
            }
        });
        txt_cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cantidadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_cantidadMousePressed(evt);
            }
        });
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 100, 30));

        jSeparator9.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator9.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 210, -1));

        jSeparator11.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator11.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 210, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Edicion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        txt_fecha.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txt_fecha.setForeground(new java.awt.Color(102, 102, 102));
        txt_fecha.setText("Ingrese la fecha");
        txt_fecha.setBorder(null);
        txt_fecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fechaFocusLost(evt);
            }
        });
        txt_fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_fechaMousePressed(evt);
            }
        });
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 210, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        txt_edicion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txt_edicion.setForeground(new java.awt.Color(120, 120, 120));
        txt_edicion.setText("Ingrese la edicion");
        txt_edicion.setBorder(null);
        txt_edicion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_edicionFocusLost(evt);
            }
        });
        txt_edicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_edicionMousePressed(evt);
            }
        });
        jPanel1.add(txt_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 210, 30));

        lbl_sesion1.setFont(new java.awt.Font("STIXIntegralsUp", 1, 24)); // NOI18N
        lbl_sesion1.setText("Libros");
        jPanel1.add(lbl_sesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, 30));

        lbl_sesion2.setFont(new java.awt.Font("STIXIntegralsUp", 0, 18)); // NOI18N
        lbl_sesion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sesion2.setText("Guardar Libro");
        lbl_sesion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_sesion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_sesion2MousePressed(evt);
            }
        });
        jPanel1.add(lbl_sesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 150, 30));

        txt_bus.setForeground(new java.awt.Color(204, 204, 204));
        txt_bus.setText("Ingrese el nombre del libro si desea modificar o borrar");
        txt_bus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_busFocusLost(evt);
            }
        });
        txt_bus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_busMousePressed(evt);
            }
        });
        jPanel1.add(txt_bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 350, 40));

        lbl_sesion3.setFont(new java.awt.Font("STIXIntegralsUp", 0, 18)); // NOI18N
        lbl_sesion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sesion3.setText("Eliminar");
        lbl_sesion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_sesion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_sesion3MousePressed(evt);
            }
        });
        jPanel1.add(lbl_sesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 100, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Insertaaa.png"))); // NOI18N
        jLabel3.setToolTipText("Seleccione para llenar los campos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 370));

        editar.setFont(new java.awt.Font("STIXIntegralsUp", 0, 18)); // NOI18N
        editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editar.setText("Editar");
        editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editarMousePressed(evt);
            }
        });
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_isbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_isbnFocusLost
        if(txt_isbn.getText().equals("")){
            txt_isbn.setText("Ingrese el ISBN");
            txt_isbn.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_isbnFocusLost

    private void txt_isbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseClicked

    private void txt_isbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseEntered

    }//GEN-LAST:event_txt_isbnMouseEntered

    private void txt_isbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseExited

    }//GEN-LAST:event_txt_isbnMouseExited

    private void txt_isbnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMousePressed
        if(txt_isbn.getText().equals("Ingrese el ISBN")){
            txt_isbn.setText("");
            txt_isbn.setForeground(Color.black);}

    }//GEN-LAST:event_txt_isbnMousePressed

    private void txt_isbnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseReleased

    private void txt_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnActionPerformed

    private void txt_tituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tituloFocusLost
        if(txt_titulo.getText().equals("")){
            txt_titulo.setText("Ingrese el Titulo");
            txt_titulo.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_tituloFocusLost

    private void txt_tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tituloMouseClicked

    }//GEN-LAST:event_txt_tituloMouseClicked

    private void txt_tituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tituloMousePressed
        if(txt_titulo.getText().equals("Ingrese el Titulo")){
            txt_titulo.setText("");
            txt_titulo.setForeground(Color.black);}
    }//GEN-LAST:event_txt_tituloMousePressed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void txt_autorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_autorFocusLost
        if(txt_autor.getText().equals("")){
            txt_autor.setText("Ingrese el autor");
            txt_autor.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_autorFocusLost

    private void txt_autorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_autorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autorMouseClicked

    private void txt_autorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_autorMousePressed

        if(txt_autor.getText().equals("Ingrese el autor")){
            txt_autor.setText("");
            txt_autor.setForeground(Color.black);}

    }//GEN-LAST:event_txt_autorMousePressed

    private void txt_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autorActionPerformed

    private void txt_editorialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_editorialFocusLost
        if(txt_editorial.getText().equals("")){
            txt_editorial.setText("Ingrese la editorial");
            txt_editorial.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_editorialFocusLost

    private void txt_editorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_editorialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editorialMouseClicked

    private void txt_editorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_editorialMousePressed
        if(txt_editorial.getText().equals("Ingrese la editorial")){
            txt_editorial.setText("");
            txt_editorial.setForeground(Color.black);}

    }//GEN-LAST:event_txt_editorialMousePressed

    private void txt_editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_editorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editorialActionPerformed

    private void txt_generoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_generoFocusLost
        if(txt_genero.getText().equals("")){
            txt_genero.setText("Ingrese el genero");
            txt_genero.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_generoFocusLost

    private void txt_generoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_generoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generoMouseClicked

    private void txt_generoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_generoMousePressed
        if(txt_genero.getText().equals("Ingrese el genero")){
            txt_genero.setText("");
            txt_genero.setForeground(Color.black);}

    }//GEN-LAST:event_txt_generoMousePressed

    private void txt_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generoActionPerformed

    private void txt_descripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_descripcionFocusLost
        if(txt_descripcion.getText().equals("")){
            txt_descripcion.setText("Ingrese alguna descripcion");
            txt_descripcion.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_descripcionFocusLost

    private void txt_descripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_descripcionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionMouseClicked

    private void txt_descripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_descripcionMousePressed
        if(txt_descripcion.getText().equals("Ingrese alguna descripcion")){
            txt_descripcion.setText("");
            txt_descripcion.setForeground(Color.black);}
    }//GEN-LAST:event_txt_descripcionMousePressed

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void txt_paginaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_paginaFocusLost
        if(txt_pagina.getText().equals("")){
            txt_pagina.setText("No. paginas");
            txt_pagina.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_paginaFocusLost

    private void txt_paginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_paginaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_paginaMouseClicked

    private void txt_paginaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_paginaMousePressed
        if(txt_pagina.getText().equals("No. paginas")){
            txt_pagina.setText("");
            txt_pagina.setForeground(Color.black);}
    }//GEN-LAST:event_txt_paginaMousePressed

    private void txt_paginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paginaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_paginaActionPerformed

    private void txt_cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadFocusLost
        if(txt_cantidad.getText().equals("")){
            txt_cantidad.setText("No. libros");
            txt_cantidad.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_cantidadFocusLost

    private void txt_cantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cantidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadMouseClicked

    private void txt_cantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cantidadMousePressed
        if(txt_cantidad.getText().equals("No. libros")){
            txt_cantidad.setText("");
            txt_cantidad.setForeground(Color.black);}
    }//GEN-LAST:event_txt_cantidadMousePressed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
    if(txt_cantidad.getText().equals("No. libros")){
            txt_cantidad.setText("");
            txt_cantidad.setForeground(Color.black);}
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed

    private void txt_fechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fechaMousePressed
    if(txt_fecha.getText().equals("Ingrese la fecha")){
            txt_fecha.setText("");
            txt_fecha.setForeground(Color.black);}
    }//GEN-LAST:event_txt_fechaMousePressed

    private void txt_fechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fechaFocusLost
    if(txt_fecha.getText().equals("")){
            txt_fecha.setText("Ingrese la fecha");
            txt_fecha.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_fechaFocusLost

    private void txt_edicionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_edicionMousePressed
    if(txt_edicion.getText().equals("Ingrese la edicion")){
            txt_edicion.setText("");
            txt_edicion.setForeground(Color.black);}
    }//GEN-LAST:event_txt_edicionMousePressed

    private void txt_edicionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_edicionFocusLost
    if(txt_edicion.getText().equals("")){
            txt_edicion.setText("Ingrese la edicion");
            txt_edicion.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_edicionFocusLost

    private void txt_busFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_busFocusLost
        if(txt_bus.getText().equals("")){
            txt_bus.setText("Ingrese el nombre del libro si desea modificar o borrar");
            txt_bus.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_busFocusLost

    private void txt_busMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_busMousePressed
    if(txt_bus.getText().equals("Ingrese el nombre del libro si desea modificar o borrar")){
            txt_bus.setText("");
            txt_bus.setForeground(Color.black);}
    }//GEN-LAST:event_txt_busMousePressed

    private void editarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarMousePressed
        String buscar = txt_bus.getText();
        int ISBN = Integer.parseInt(txt_isbn.getText());
        String autor = txt_autor.getText();
        int cantidad = Integer.parseInt(txt_cantidad.getText());
        String editorial  = txt_editorial.getText();
        String genero = txt_genero.getText();
        String fecha = txt_fecha.getText();
        int paginas = Integer.parseInt(txt_pagina.getText());
        String edicion = txt_edicion.getText();
        String titulo = txt_titulo.getText();
            try{
                Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
                String insertarsql = "UPDATE Libros SET Autor = '"+autor+"',Cant="+cantidad+",Editorial='"+editorial+"',Genero='"+genero+"',FechaPublicacion='"+fecha+"',Paginas="+paginas+",Edicion='"+edicion+"',NombreLibro='"+titulo+"', ISBN="+ISBN+" WHERE NombreLibro='"+buscar+"';";
                sql.executeQuery(insertarsql);
                }catch(SQLException | NumberFormatException e){
                    System.out.println(e.toString());
            }
    JOptionPane.showMessageDialog(null,"Editado");
    }//GEN-LAST:event_editarMousePressed

    private void lbl_sesion2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sesion2MousePressed
    int ISBN = Integer.parseInt(txt_isbn.getText());
        String autor = txt_autor.getText();
        int cantidad = Integer.parseInt(txt_cantidad.getText());
        String editorial  = txt_editorial.getText();
        String genero = txt_genero.getText();
        String fecha = txt_fecha.getText();
        int paginas = Integer.parseInt(txt_pagina.getText());
        String edicion = txt_edicion.getText();
        String titulo = txt_titulo.getText();
            try{
                Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
                String insertarsql = "INSERT INTO Libros(ISBN,FechaPublicacion,Edicion,NombreLibro,Genero,Editorial,Autor,Cant,Paginas)VALUES("+ISBN+",'"+fecha+"','"+edicion+"','"+titulo+"','"+genero+"','"+editorial+"','"+autor+"',"+cantidad+","+paginas+")";
                sql.executeQuery(insertarsql);
                }catch(SQLException | NumberFormatException e){
                    System.out.println(e.toString());
            }
    }//GEN-LAST:event_lbl_sesion2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
    String buscar = txt_bus.getText();
    try{
        Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
        String buscarsql = "SELECT * FROM dbo.Libros WHERE NombreLibro='"+buscar+"'";
        ResultSet rs = sql.executeQuery(buscarsql);
        rs.next();
            txt_isbn.setText(rs.getString("ISBN"));
            //txt_isbn.setText(rs.getString("ISBN"));
            txt_fecha.setText(rs.getString("FechaPublicacion"));
            txt_edicion.setText(rs.getString("Edicion"));
            txt_titulo.setText(rs.getString("NombreLibro"));
            txt_cantidad.setText(rs.getString("Cant"));
            txt_pagina.setText(rs.getString("Paginas"));
            txt_editorial.setText(rs.getString("Editorial"));
            txt_genero.setText(rs.getString("Genero"));
            txt_autor.setText(rs.getString("Autor"));
    }catch(SQLException e){
        System.out.println(e.toString());
    } 
    }//GEN-LAST:event_jLabel3MousePressed

    private void lbl_sesion3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sesion3MousePressed
    String buscar = txt_bus.getText();
    try{
        Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
        String buscarsql = "DELETE FROM Libros WHERE NombreLibro='"+buscar+"'";
        ResultSet rs = sql.executeQuery(buscarsql);
    }catch(SQLException e){
        System.out.println(e.toString());
    }
    JOptionPane.showMessageDialog(null,"Eliminado");
    }//GEN-LAST:event_lbl_sesion3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_editorial;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_pagina;
    private javax.swing.JLabel lbl_sesion1;
    private javax.swing.JLabel lbl_sesion2;
    private javax.swing.JLabel lbl_sesion3;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_bus;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_edicion;
    private javax.swing.JTextField txt_editorial;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_pagina;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
