/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IG;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author perla
 */
public class Prestamo extends javax.swing.JPanel {

    /**
     * Creates new form Borrar_Libro
     */
    public Prestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_isbn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_titulo = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_usuario1 = new javax.swing.JLabel();
        lbl_bus1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_bus2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txt_fecha1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txt_isbn1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_usuario2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(669, 503));
        setPreferredSize(new java.awt.Dimension(669, 503));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_isbn.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_isbn.setForeground(new java.awt.Color(153, 153, 153));
        txt_isbn.setText("Clave unica del libro");
        txt_isbn.setToolTipText("Ingrese el ISBN");
        txt_isbn.setBorder(null);
        txt_isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_isbnFocusLost(evt);
            }
        });
        txt_isbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_isbnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_isbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_isbnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_isbnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_isbnMouseReleased(evt);
            }
        });
        txt_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbnActionPerformed(evt);
            }
        });
        add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 210, 30));

        jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 210, -1));

        lbl_titulo.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_titulo.setText("Ingrese nombre de usuario");
        add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        txt_usuario.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(153, 153, 153));
        txt_usuario.setText("Nombre de usuario");
        txt_usuario.setBorder(null);
        txt_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usuarioFocusLost(evt);
            }
        });
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 210, 30));

        jSeparator2.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 210, -1));

        lbl_usuario1.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_usuario1.setText("ISBN");
        add(lbl_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lbl_bus1.setFont(new java.awt.Font("STIXIntegralsUp", 0, 24)); // NOI18N
        lbl_bus1.setText("Prestar");
        lbl_bus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_bus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_bus1MousePressed(evt);
            }
        });
        add(lbl_bus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iStock.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 350, 320));

        lbl_bus2.setFont(new java.awt.Font("STIXIntegralsUp", 1, 36)); // NOI18N
        lbl_bus2.setForeground(new java.awt.Color(153, 102, 0));
        lbl_bus2.setText("El Barco De Papel");
        add(lbl_bus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 320, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Entrega");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        txt_fecha.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txt_fecha.setForeground(new java.awt.Color(102, 102, 102));
        txt_fecha.setBorder(null);
        txt_fecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fechaFocusLost(evt);
            }
        });
        txt_fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_fechaMousePressed(evt);
            }
        });
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });
        add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 210, 30));

        jSeparator11.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator11.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 210, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Devolucion");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        txt_fecha1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txt_fecha1.setForeground(new java.awt.Color(102, 102, 102));
        txt_fecha1.setBorder(null);
        txt_fecha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fecha1FocusLost(evt);
            }
        });
        txt_fecha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_fecha1MousePressed(evt);
            }
        });
        txt_fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha1ActionPerformed(evt);
            }
        });
        add(txt_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 210, 30));

        jSeparator12.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator12.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 210, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 300, 10));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 120, -1, 340));

        txt_isbn1.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_isbn1.setForeground(new java.awt.Color(153, 153, 153));
        txt_isbn1.setToolTipText("Ingrese el ISBN");
        txt_isbn1.setBorder(null);
        txt_isbn1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_isbn1FocusLost(evt);
            }
        });
        txt_isbn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_isbn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_isbn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_isbn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_isbn1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_isbn1MouseReleased(evt);
            }
        });
        txt_isbn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbn1ActionPerformed(evt);
            }
        });
        add(txt_isbn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 210, 30));

        jSeparator4.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 210, -1));

        lbl_usuario2.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_usuario2.setText("ID prestamo");
        add(lbl_usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_isbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_isbnFocusLost
        if(txt_isbn.getText().equals("")){
            txt_isbn.setText("Clave unica del libro");
            txt_isbn.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_isbnFocusLost

    private void txt_isbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseClicked

    private void txt_isbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseEntered

    }//GEN-LAST:event_txt_isbnMouseEntered

    private void txt_isbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseExited

    }//GEN-LAST:event_txt_isbnMouseExited

    private void txt_isbnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMousePressed
        if(txt_isbn.getText().equals("Clave unica del libro")){
            txt_isbn.setText("");
            txt_isbn.setForeground(Color.black);}
    }//GEN-LAST:event_txt_isbnMousePressed

    private void txt_isbnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseReleased

    private void txt_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnActionPerformed

    private void txt_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usuarioFocusLost
        if(txt_usuario.getText().equals("")){
            txt_usuario.setText("Nombre de usuario");
            txt_usuario.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_usuarioFocusLost

    private void txt_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseClicked

    }//GEN-LAST:event_txt_usuarioMouseClicked

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMousePressed
        if(txt_usuario.getText().equals("Nombre de usuario")){
            txt_usuario.setText("");
            txt_usuario.setForeground(Color.black);}
    }//GEN-LAST:event_txt_usuarioMousePressed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_fechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fechaFocusLost
        if(txt_fecha.getText().equals("")){
            txt_fecha.setText("Ingrese la fecha");
            txt_fecha.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_fechaFocusLost

    private void txt_fechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fechaMousePressed
        if(txt_fecha.getText().equals("Ingrese la fecha")){
            txt_fecha.setText("");
            txt_fecha.setForeground(Color.black);}
    }//GEN-LAST:event_txt_fechaMousePressed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed

    private void txt_fecha1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fecha1FocusLost
        if(txt_fecha.getText().equals("")){
            txt_fecha.setText("Ingrese la fecha");
            txt_fecha.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_fecha1FocusLost

    private void txt_fecha1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fecha1MousePressed
        if(txt_fecha.getText().equals("Ingrese la fecha")){
            txt_fecha.setText("");
            txt_fecha.setForeground(Color.black);}
    }//GEN-LAST:event_txt_fecha1MousePressed

    private void txt_fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha1ActionPerformed

    
    /****
     Hacer 
     INSERT INTO Multa(IDMulta,CostoMulta)
      VALUES(01,200)
    *****/

    
    private void lbl_bus1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bus1MousePressed
    int isbn = Integer.parseInt(txt_isbn.getText());
    //int id_us = Integer.parseInt(txt_name.getText());
    int cantidad_actual = 0;
        try {
            Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
            String insertarsql2 = "SELECT Cant FROM dbo.Libros WHERE ISBN=" + isbn + ";";
            ResultSet rs = sql.executeQuery(insertarsql2);
            rs.next();
            cantidad_actual = rs.getInt("Cant");
            cantidad_actual = cantidad_actual - 1;
               System.out.println(cantidad_actual);
            String insertarsql = "UPDATE dbo.Libros SET Cant=" + cantidad_actual + " WHERE ISBN='" + isbn + "';";
            sql.executeQuery(insertarsql);
        } catch (SQLException | NumberFormatException e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lbl_bus1MousePressed

    private void txt_isbn1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_isbn1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbn1FocusLost

    private void txt_isbn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbn1MouseClicked

    private void txt_isbn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbn1MouseEntered

    private void txt_isbn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbn1MouseExited

    private void txt_isbn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbn1MousePressed

    private void txt_isbn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbn1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbn1MouseReleased

    private void txt_isbn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_bus1;
    private javax.swing.JLabel lbl_bus2;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_usuario1;
    private javax.swing.JLabel lbl_usuario2;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_fecha1;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_isbn1;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
