/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IG;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author perla
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        txt_cantidad = new javax.swing.JTextField();
        lbl_cantidad = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_genero = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_titulo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_isbn = new javax.swing.JTextField();
        lbl_usuario = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        lbl_bus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSeparator8.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));

        txt_cantidad.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_cantidad.setForeground(new java.awt.Color(153, 153, 153));
        txt_cantidad.setText("No. libros");
        txt_cantidad.setBorder(null);
        txt_cantidad.setFocusCycleRoot(true);
        txt_cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cantidadFocusLost(evt);
            }
        });
        txt_cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cantidadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_cantidadMousePressed(evt);
            }
        });
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        lbl_cantidad.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_cantidad.setText("Cantidad");

        txt_genero.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_genero.setForeground(new java.awt.Color(153, 153, 153));
        txt_genero.setText("Genero de libro");
        txt_genero.setBorder(null);
        txt_genero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_generoFocusLost(evt);
            }
        });
        txt_genero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_generoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_generoMousePressed(evt);
            }
        });
        txt_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_generoActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator5.setForeground(new java.awt.Color(51, 153, 255));

        lbl_genero.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_genero.setText("Genero");

        jSeparator2.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));

        txt_titulo.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(153, 153, 153));
        txt_titulo.setText("Titulo del libro");
        txt_titulo.setBorder(null);
        txt_titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tituloFocusLost(evt);
            }
        });
        txt_titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tituloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_tituloMousePressed(evt);
            }
        });
        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        lbl_titulo.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_titulo.setText("Titulo");

        jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));

        txt_isbn.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_isbn.setForeground(new java.awt.Color(153, 153, 153));
        txt_isbn.setText("Clave unica del libro");
        txt_isbn.setToolTipText("Ingrese el ISBN");
        txt_isbn.setBorder(null);
        txt_isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_isbnFocusLost(evt);
            }
        });
        txt_isbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_isbnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_isbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_isbnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_isbnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_isbnMouseReleased(evt);
            }
        });
        txt_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbnActionPerformed(evt);
            }
        });

        lbl_usuario.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_usuario.setText("ISBN");

        txt_bus.setForeground(new java.awt.Color(204, 204, 204));
        txt_bus.setText("Ingrese el nombre del libro");
        txt_bus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_busFocusLost(evt);
            }
        });
        txt_bus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_busMousePressed(evt);
            }
        });

        lbl_bus.setFont(new java.awt.Font("STIXIntegralsUp", 1, 24)); // NOI18N
        lbl_bus.setText("Buscador de libros");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/336799ebb339821f342bc5a13386aff2.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Insertaaa.png"))); // NOI18N
        jLabel3.setToolTipText("Seleccione para llenar los campos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_bus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cantidad)
                            .addComponent(lbl_usuario)
                            .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_titulo)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_genero)
                            .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbl_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_usuario)
                                .addGap(1, 1, 1)
                                .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(lbl_titulo)
                                .addGap(1, 1, 1)
                                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(lbl_genero)
                                .addGap(1, 1, 1)
                                .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_cantidad)
                                .addGap(3, 3, 3)
                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadFocusLost
        if(txt_cantidad.getText().equals("")){
            txt_cantidad.setText("No. libros");
            txt_cantidad.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_cantidadFocusLost

    private void txt_cantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cantidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadMouseClicked

    private void txt_cantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cantidadMousePressed
        if(txt_cantidad.getText().equals("No. libros")){
            txt_cantidad.setText("");
            txt_cantidad.setForeground(Color.black);}
    }//GEN-LAST:event_txt_cantidadMousePressed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_generoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_generoFocusLost
        if(txt_genero.getText().equals("")){
            txt_genero.setText("Genero de libro");
            txt_genero.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_generoFocusLost

    private void txt_generoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_generoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generoMouseClicked

    private void txt_generoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_generoMousePressed
        if(txt_genero.getText().equals("Genero de libro")){
            txt_genero.setText("");
            txt_genero.setForeground(Color.black);}
    }//GEN-LAST:event_txt_generoMousePressed

    private void txt_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generoActionPerformed

    private void txt_tituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tituloFocusLost
        if(txt_titulo.getText().equals("")){
            txt_titulo.setText("Titulo del libro");
            txt_titulo.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_tituloFocusLost

    private void txt_tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tituloMouseClicked

    }//GEN-LAST:event_txt_tituloMouseClicked

    private void txt_tituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tituloMousePressed
        if(txt_titulo.getText().equals("Titulo del libro")){
            txt_titulo.setText("");
            txt_titulo.setForeground(Color.black);}
    }//GEN-LAST:event_txt_tituloMousePressed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void txt_isbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_isbnFocusLost
        if(txt_isbn.getText().equals("")){
            txt_isbn.setText("Clave unica del libro");
            txt_isbn.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_isbnFocusLost

    private void txt_isbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseClicked

    private void txt_isbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseEntered

    }//GEN-LAST:event_txt_isbnMouseEntered

    private void txt_isbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseExited

    }//GEN-LAST:event_txt_isbnMouseExited

    private void txt_isbnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMousePressed
        if(txt_isbn.getText().equals("Clave unica del libro")){
            txt_isbn.setText("");
            txt_isbn.setForeground(Color.black);}
    }//GEN-LAST:event_txt_isbnMousePressed

    private void txt_isbnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnMouseReleased

    private void txt_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnActionPerformed

    private void txt_busFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_busFocusLost
        if(txt_bus.getText().equals("")){
            txt_bus.setText("Ingrese el nombre del libro");
            txt_bus.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_busFocusLost

    private void txt_busMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_busMousePressed
        if(txt_bus.getText().equals("Ingrese el nombre del libro")){
            txt_bus.setText("");
            txt_bus.setForeground(Color.black);}
    }//GEN-LAST:event_txt_busMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
    String buscar = txt_bus.getText();
    try{
        Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
        String buscarsql = "SELECT * FROM dbo.Libros WHERE NombreLibro='"+buscar+"'";
        ResultSet rs = sql.executeQuery(buscarsql);
        rs.next();
            txt_isbn.setText(rs.getString("ISBN"));
            //txt_fecha.setText(rs.getString("FechaPublicacion"));
            //txt_edicion.setText(rs.getString("Edicion"));
            txt_titulo.setText(rs.getString("NombreLibro"));
            txt_cantidad.setText(rs.getString("Cant"));
            //txt_pagina.setText(rs.getString("Paginas"));
            //txt_editorial.setText(rs.getString("Editorial"));
            txt_genero.setText(rs.getString("Genero"));
            //txt_autor.setText(rs.getString("Autor"));
    }catch(SQLException e){
        System.out.println(e.toString());
    } 
    }//GEN-LAST:event_jLabel3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbl_bus;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_bus;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
