/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IG;

import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author perla
 */
public class Registro_ini extends javax.swing.JFrame {
    
    Inicio cio = new Inicio();
    
    
    /**
     * Creates new form Registro_ini
     */
    public Registro_ini() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_sesion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JTextField();
        lbl_tipo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_contra = new javax.swing.JPasswordField();
        lbl_contra = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl_salir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cb_turno = new javax.swing.JComboBox<>();
        lbl_turno = new javax.swing.JLabel();
        lbl_sesion2 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sesion.setFont(new java.awt.Font("STIXIntegralsUp", 1, 24)); // NOI18N
        lbl_sesion.setText("Registro");
        jPanel1.add(lbl_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 110, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 320, -1));

        txt_usuario.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(102, 102, 102));
        txt_usuario.setText("Ingrese su usuario");
        txt_usuario.setBorder(null);
        txt_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usuarioFocusLost(evt);
            }
        });
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 320, 30));

        lbl_tipo.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_tipo.setText("TIPO DE USUARIO");
        jPanel1.add(lbl_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 10));

        txt_contra.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_contra.setForeground(new java.awt.Color(204, 204, 204));
        txt_contra.setText("Ingrese la contraseña");
        txt_contra.setBorder(null);
        txt_contra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contraFocusLost(evt);
            }
        });
        txt_contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_contraMousePressed(evt);
            }
        });
        jPanel1.add(txt_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 320, -1));

        lbl_contra.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_contra.setText("CONTRASEÑA");
        jPanel1.add(lbl_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lbl_usuario.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_usuario.setText("USUARIO");
        jPanel1.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 320, -1));

        lbl_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regresar.png"))); // NOI18N
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, 420));

        cb_turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino" }));
        cb_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_turnoActionPerformed(evt);
            }
        });
        jPanel1.add(cb_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 320, -1));

        lbl_turno.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_turno.setText("Turno");
        jPanel1.add(lbl_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        lbl_sesion2.setFont(new java.awt.Font("STIXIntegralsUp", 0, 18)); // NOI18N
        lbl_sesion2.setText("Guardar");
        lbl_sesion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_sesion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_sesion2MousePressed(evt);
            }
        });
        jPanel1.add(lbl_sesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 70, 30));

        lbl_id.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_id.setText("Id:");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txt_id.setBorder(null);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 270, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 320, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 320, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_sesion2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sesion2MousePressed
        int id = Integer.parseInt(txt_id.getText());
        int admin = 1;
        String nombre = txt_usuario.getText();
        String contra  = txt_contra.getText();
        if(jComboBox1.getSelectedItem().toString().equals("Administrador")){
            admin = 1;
        }
        else{
            admin = 0;
        }
        String turno = cb_turno.getSelectedItem().toString();
        String email = "prueba@email.com";
        String dir = "dir prueba";
        String numtel = "12345";
            try{
                Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
                String insertarsql = "INSERT INTO Bibliotecario(IDBibliotecario, Nombre, Email, Direccion, NumTel, Turno, Contra, AdminRol) VALUES("+id+",'"+nombre+"','"+email+"','"+dir+"','"+numtel+"','"+turno+"','"+contra+"',"+admin+")";
                sql.executeQuery(insertarsql);
                }catch(SQLException | NumberFormatException e){
                    System.out.println(e.toString());
            }
            JOptionPane.showMessageDialog(null,"Registrado");
    }//GEN-LAST:event_lbl_sesion2MousePressed

    private void cb_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_turnoActionPerformed

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        Sesion s= new Sesion();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void txt_contraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contraMousePressed
        if(txt_contra.getText().equals("Ingrese la contraseña")){
            txt_contra.setText("");
            txt_contra.setForeground(Color.black);}
    }//GEN-LAST:event_txt_contraMousePressed

    private void txt_contraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contraFocusLost
        if(txt_contra.getText().equals("")){
            txt_contra.setText("Ingrese la contraseña");
            txt_contra.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_contraFocusLost

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMousePressed
        if(txt_usuario.getText().equals("Ingrese su usuario")){
            txt_usuario.setText("");
            txt_usuario.setForeground(Color.black);}
    }//GEN-LAST:event_txt_usuarioMousePressed

    private void txt_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usuarioFocusLost
        if(txt_usuario.getText().equals("")){
            txt_usuario.setText("Ingrese su usuario");
            txt_usuario.setForeground(Color.GRAY);}
    }//GEN-LAST:event_txt_usuarioFocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_ini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_turno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_contra;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JLabel lbl_sesion;
    private javax.swing.JLabel lbl_sesion2;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_turno;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_contra;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
