/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IG;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author aylin
 */
public class Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Sesion
     */
    public Sesion() {
        //jButton1.setVisible(false);
        initComponents();
        //lbl_usuario.setVisible(false);
    }

    /**
     *  String bases ="";
        try{
            Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
            String consulta ="SELECT name FROM master.dbo.sysdatabases";
            ResultSet resultado = sql.executeQuery(consulta);

            while(resultado.next()){
                bases += resultado.getString(1) + "\n";
            }
            JOptionPane.showMessageDialog(null, bases);
        }catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.toString());

        }
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_imagenI = new javax.swing.JLabel();
        lbl_sesion = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_contra = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        cmd_entrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_salir = new javax.swing.JLabel();
        lbl_sesion1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_imagenI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/libreria2.jpeg"))); // NOI18N
        jPanel1.add(lbl_imagenI, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 350, 440));

        lbl_sesion.setFont(new java.awt.Font("STIXIntegralsUp", 0, 18)); // NOI18N
        lbl_sesion.setText("Registrar");
        lbl_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_sesionMousePressed(evt);
            }
        });
        jPanel1.add(lbl_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 80, 30));

        lbl_usuario.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_usuario.setText("USUARIO");
        jPanel1.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txt_user.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_user.setForeground(new java.awt.Color(102, 102, 102));
        txt_user.setText("Ingrese su usuario");
        txt_user.setBorder(null);
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_userMousePressed(evt);
            }
        });
        jPanel1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 207, 320, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 237, 320, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 320, 10));

        lbl_contra.setFont(new java.awt.Font("STIXIntegralsUp", 0, 14)); // NOI18N
        lbl_contra.setText("CONTRASEÑA");
        jPanel1.add(lbl_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txt_pass.setFont(new java.awt.Font("STIXIntegralsUp", 0, 13)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(204, 204, 204));
        txt_pass.setText("Ingrese la contra");
        txt_pass.setBorder(null);
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_passMousePressed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 320, -1));

        cmd_entrar.setBackground(new java.awt.Color(153, 102, 0));
        cmd_entrar.setForeground(new java.awt.Color(166, 110, 0));
        cmd_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmd_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_entrarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmd_entrarMousePressed(evt);
            }
        });
        cmd_entrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("STIXIntegralsUp", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Entrar");
        cmd_entrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(cmd_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 110, 40));

        lbl_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir2.png"))); // NOI18N
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        lbl_sesion1.setFont(new java.awt.Font("STIXIntegralsUp", 1, 24)); // NOI18N
        lbl_sesion1.setText("INICIAR SESIÓN");
        jPanel1.add(lbl_sesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMousePressed
        if(txt_user.getText().equals("Ingrese su usuario")){
            txt_user.setText("");
            txt_user.setForeground(Color.black);}

        if(String.valueOf(txt_pass.getPassword()).isEmpty()){
            txt_pass.setText("Ingrese la contra");
            txt_pass.setForeground(Color.gray);}
    }//GEN-LAST:event_txt_userMousePressed

    private void txt_passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMousePressed
        if(String.valueOf(txt_pass.getPassword()).equals("Ingrese la contra")){
            txt_pass.setText("");
            txt_pass.setForeground(Color.black);}

        if(txt_user.getText().isEmpty()){
            txt_user.setText("Ingrese su usuario");
            txt_user.setForeground(Color.gray);}
    }//GEN-LAST:event_txt_passMousePressed

    private void cmd_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_entrarMouseClicked
        
    }//GEN-LAST:event_cmd_entrarMouseClicked

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void lbl_sesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sesionMousePressed
        Registro_ini ri = new Registro_ini();
        ri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_sesionMousePressed

    private void cmd_entrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_entrarMousePressed
        String user = txt_user.getText();
        String pass  = txt_pass.getText();
        String v1 = "";
        String v2 = "";
        try{
            Statement sql = ConnectionSQL.getConnectionSQL().createStatement();
            String buscarsql = "SELECT * FROM Bibliotecario WHERE Nombre='"+user+"' AND Contra='"+pass+"'";
            ResultSet rs = sql.executeQuery(buscarsql);
            rs.next();
            v1 = rs.getString("Nombre");
            v2 = rs.getString("Contra");
            }catch(SQLException | NumberFormatException e){
            System.out.println(e.toString());
        }
        if(v1.equals(user)&& v2.equals(pass)){
            Inicio ini = new Inicio();
            ini.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cmd_entrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cmd_entrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_contra;
    private javax.swing.JLabel lbl_imagenI;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JLabel lbl_sesion;
    private javax.swing.JLabel lbl_sesion1;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
